### ISSUE TITLE
Move to spamgourmet organisation

### ISSUE THREAD

**Issue by mikedlr** [spamgourmet/spamgourmet-clone#4]
@eegeeZA I'm also a long term spamgourmet user / supporter.  I now have the spamgourmet organisation name on GitHub.  I'd propose keeping the source code under that.  I'm going to send you an invite and if you come in give you read/write/admin access.  I'll keep control of the ownership of the organisation but would be happy to transfer it to the spamgourmet administrators if they ask.  

See also [discussion on the forum](https://bbs.spamgourmet.com/viewtopic.php?f=2&t=1787&p=8263&sid=d80f35177a3b9ef559172f66de900cb7#p8263)

**Comment by nrbray** [comment]
https://github.com/spamgourmet looks to be a good name for a team to use - happy to help if it moves there or stays with https://github.com/eegeeZA/spamgourmet-clone

best to settle on one!

**Comment by mikedlr** [comment]
I'd definitely prefer it to be an an organisation rather than a personal account so that if one person becomes unavailable then other people can work on.

**Comment by jgonggrijp** [comment]
> I'd definitely prefer it to be an an organisation rather than a personal account so that if one person becomes unavailable then other people can work on.

I'm not opposed to a transfer to the @spamgourmet organization, but I'd like to add a nuance here: even in case of a personal account, other people can work on when the owner of the account becomes unavailable. Working on a fork may look a bit less representative, but it still works and you can also send pull requests to other forks.

**Comment by eegeeZA** [comment]
Hi @mikedlr, I originally created the clone when I found out that spamgourmet was going to be shutdown. I wanted to make sure that there was a modern public copy in Git of the SVN code.

Will the organisation and it's members be public too? I see that [spamgourmet](https://github.com/orgs/spamgourmet/people) does not have any public members, nor does [spamgourmet-com](https://github.com/orgs/spamgourmet-com/people) for which I received an invite last month. How will the members and their roles be defined?

**Comment by mikedlr** [comment]
@eegeeZA I'm not sure what you want from the organisation being public?  I would normally assume so, but since you are the primary developer currently I'll do it pretty much as you wish (if there was an actual organisation with multiple people and someone asked I'd probably put this to a vote).

For now I will do more or less anything you wish including admin but excepting ownership of the org.  For that I'd like to wait till we get some message from the new administrators of spamgourmet.  

So, is that okay?

**Comment by eegeeZA** [comment]
The intention behind keeping the organisation public is just for transparency. From an outsider's perspective, I would like to quickly see all the parties involved with an ability to edit the code. The more people involved, the more requirements/governance/votes required for making changes, deleting a repository, etc.

I am happy with waiting until you receive feedback before transferring ownership of the repository. It is simpler that way and less hassle.

**Comment by mikedlr** [comment]
Great; we are on the same page.  This is my standard GitHub account and clearly linked to me and my real identity.  I'm actively happy to stand up for spamgourmet and I regularly publicise it.  At the same time, I think there are lots of legitimate users of spamgourment and potential contributors who don't want transparency - they use spamgourmet for privacy and don't want to give away their identity. 

I think we can support such people fine.  We recommend they register a second GitHub account using a private email address or they proxy through one of us.  Merges should happen from people who are reasonably traceable and willing to at least try to audit code.

**Comment by mikedlr** [comment]
I have resent an invite to @eegeeZA since I think the old invite I sent expired.  I also invited @nrbray, @jgonggrijp and @shinyone.   Please join the organisation reasonably quickly so that the invitation does not expire (you can always leave later if you decide this was a bad idea :-) )  If you don't see the invite in mail please visit [https://github.com/spamgourmet](https://github.com/spamgourmet) to accept the invitation.

If the repo transfers over I'd suggest a) renaming it spamgourmet and b) making @eegeeZA the repo admin.  It might be a good idea to set up some rules for PRs, which I can do on request from @eegeeZA

**Comment by mikedlr** [comment]
I've been through the project settings to increase transparency and security.  I turned off various things (e.g. transfer repo ownership for admins).  Although I managed to make my own organisation membership public, it seems that [enforcing visible membership is a GitHub Enterprise feature only](https://help.github.com/en/enterprise/2.17/admin/user-management/configuring-visibility-for-organization-membership) so I can't do that.  The best we can do is check from time to time and agree to move members who aren't visible to read-only mode.  Is that fine with everyone.

**Comment by jgonggrijp** [comment]
I accepted the invitation and set my own membership to public.

I would like to say a few things about membership, continuity and transparency.

First of all, in an organisation that only has public repos, like @spamgourmet, there is no practical difference between a non-member and a read-only member. For this reason, I don't think it would make much sense to demote members to read-only.

Secondly, even if your membership is private, your contributions are still as public as the repo. So if, for example, a private member merges a pull request in a public repo, everyone will be able to see this and infer that this person was apparently given write access to the repo in question. Basically, this means that private membership has no real privacy benefits in a completely public organisation. Unless you never exercise your privileges, but as I said before, in that case there is no added value in being a member in the first place.

Thirdly, in public repos, membership is not required for regular contributions. You can open and reply to issues, fork the repo, create pull requests and even review PRs by other people without being a member.

Fourthly, an organization can have multiple owners and I think this would be a good thing. I think we need to trust each other to some extend. We all have the same goal: we want to keep spamgourmet in the air. I don't think anyone who has participated in this thread so far would want to harm this goal. Of course, anyone with power can make a mistake at any time, but I think we can trust this person to rectify the mistake when that happens. The worst that can happen is that somebody deletes the repo or locks out everybody else (which is more or less equivalent); but GitHub makes neither of those actions easy to perform by accident and in the unlikely event that it actually happens, we still have our forks and local clones, so we can just start over.

Given these considerations, I would like to suggest a slightly different policy with regard to membership and transparency:

- The primary purpose of membership should be governance (rather than regular contributions). In particular, members are the people who triage issues, merge or close pull requests and create releases.
- Given the primary purpose, being a private member does not really protect your privacy. This is something that should be made very clear in advance to prospective members. If a developer does not want her name to be publicly associated with spamgourmet, she will need to use a pseudonym, not only for governance but also for regular commits, issue comments etcetera.
- If we find that somebody's membership is set to private, I think there is no point in demoting her to read-only, but we can invite her in a friendly way to make it public. This is something that should also be done before she becomes a member. If she insists on staying private and also does not use her membership privileges, then she effectively does not behave like a member and she can be removed from the organisation altogether.
- To promote transparency, I would like to suggest that all code contributions, including those by members, should be made through a pull request and should be reviewed by another developer (member or non-member).
- To promote continuity, I think there should always be at least two owners, so that if one of them falls away for whatever reason, the other is still there to arrange things and can appoint a new colleague. Initially, this could be @mikedlr and @eegeeZA. If the new spamgourmet.com admin reveals himself, he can join them as a third owner.

Regarding the last point, we should try to prevent a situation where we are fussing over a GitHub repo while the new admin continues using the old SVN repo. Maybe one of us should try to reach out to the people who have used the SVN repo in the past and those who might use it in the future. Basically the people with "development" in [this list](https://www.spamgourmet.com/index.pl?printpage=team.html) plus the new admin. I hereby offer to do that.

Please let me know what you think.

**Comment by nrbray** [comment]
> The intention behind keeping the organisation public is just for transparency. From an outsider's perspective, I would like to quickly see all the parties involved with an ability to edit the code. The more people involved, the more requirements/governance/votes required for making changes, deleting a repository, etc.

I too support keeping the organisation public.

> 
> I am happy with waiting until you receive feedback before transferring ownership of the repository. It is simpler that way and less hassle.

All OK from what I have seen so far but will reply to show my support.

**Comment by nrbray** [comment]
> ...I also invited @nrbray, ..
Thank you

> If the repo transfers over I'd suggest a) renaming it spamgourmet and b) making @eegeeZA the repo admin. It might be a good idea to set up some rules for PRs, which I can do on request from @eegeeZA

Happy with that, and perhaps note @jgonggrijp's offer to reach out to avoid a situation where the new admin continues using the old SVN repo instead

**Comment by nrbray** [comment]
@jgonggrijp Appreciate your comments and also your earlier pull requests, especially the link to vasile-gh's cloning script 

> reach out to the people who have used the SVN repo in the past and those who might use it in the future. Basically the people with "development" in this list plus the new admin. I hereby offer to do that.

I would support your kind offer and thank you

> * invite [potential members] in a friendly way to make [their membership] public.

no problem with that and while I see your logic of avoiding read-only members in the interests of low ceremony offer a minor suggestion it may also be ok if after best effort it happens live with someone not doing that and perhaps agree to move members who aren't visible to read-only mode unless and until they are public

**Comment by mikedlr** [comment]
@jgonggrijp yes please, reach out.  Please note that nobody has responded to posts by either of us on the forum.  I worry this may be because they don't have the time and I don't want to in any way upset Josh's family.  Please do it in a way that takes into account that they may be having a difficult time.  

Happy to add @eegeeZA as owner but would like some legally binding but non-problematic (short, simple and without burden to the people agreeing) agreement that the ownership would be used in support of the aims of spamgourmet.  I'd rather put this off for a little while when it's clear that we have got this started as software.

**Comment by mikedlr** [comment]
@jgonggrijp the primary difference between a member and non member would be that a member could merge a pull request.  Even more than owners, that's a community it's crucial to keep live.  For the rest of it, I agree.  

Given your comments about private repos I'm largely convinced that if the member has her membership private then that's not a problem.  I withdraw the earlier suggestion.

**Comment by jgonggrijp** [comment]
@nrbray:

> @jgonggrijp Appreciate your comments and also your earlier pull requests, especially the link to vasile-gh's cloning script

Thanks.

> > * invite [potential members] in a friendly way to make [their membership] public.
> 
> no problem with that and while I see your logic of avoiding read-only members in the interests of low ceremony offer a minor suggestion it may also be ok if after best effort it happens live with someone not doing that and perhaps agree to move members who aren't visible to read-only mode unless and until they are public

Do you mean: make all new members read-only by default and only give them write access once they have made their membership public? I think that would be an elegant way to avoid all the problems we have discussed so far, especially if we clearly inform people about this procedure in advance.

@mikedlr:

> @jgonggrijp yes please, reach out. Please note that nobody has responded to posts by either of us on the forum. I worry this may be because they don't have the time and I don't want to in any way upset Josh's family. Please do it in a way that takes into account that they may be having a difficult time.

Thanks for the reminder, I agree that's very important. I'll make sure to take this into account.

> Happy to add @eegeeZA as owner but would like some legally binding but non-problematic (short, simple and without burden to the people agreeing) agreement that the ownership would be used in support of the aims of spamgourmet. I'd rather put this off for a little while when it's clear that we have got this started as software.

Fine by me if you want to postpone this a bit. We are not exactly in a hurry here. We can take our time to come to an agreement that everyone is comfortable with.

Regarding legal binding, I'm far from a legal expert, but I suspect this might be very difficult to ensure in an international setting. You might need some kind of specialized law person for that. Also, are you really going to sue someone if he breaks the agreement? It might be more practical and cheaper for us all to just trust each other and make sure that we can recover if somebody defects. With the redundancy that git offers out of the box, recovering doesn't seem very hard.

About @eegeeZA in particular: in my opinion, he or she<sup>$</sup> has already proven to share the same goal by taking the effort to create a GitHub clone and by accepting our pull requests. I think you can trust him/her<sup>$</sup>.

> @jgonggrijp the primary difference between a member and non member would be that a member could merge a pull request. Even more than owners, that's a community it's crucial to keep live. For the rest of it, I agree.

To me, that looks like we agree 100% without exceptions. I might have been a bit unclear somewhere; sorry about that.

> Given your comments about private repos I'm largely convinced that if the member has her membership private then that's not a problem. I withdraw the earlier suggestion.

How about making all new members read-only by default and then lifting them to write access ("activating" their membership, so to speak) as soon as they make their membership public, as discussed above with @nrbray?

---
<sup>$</sup> Which pronoun do you prefer, @eegeeZA?

**Comment by jgonggrijp** [comment]
Just after posting the above, I read the shutdown announcement thread again and I noticed two things that are relevant here and which I had forgotten about in the meanwhile.

[josh, Thu Aug 22, 2019 11:40 pm](https://bbs.spamgourmet.com/viewtopic.php?p=8200#p8200):

> (...) I can't seem to log into source forge anymore (...)

So the old SVN repo is not really an alternative to this GitHub repo, anyway. This simplifies the message I'll be reaching out with a bit.

[eegee, Fri Aug 23, 2019 8:05 pm](https://bbs.spamgourmet.com/viewtopic.php?p=8210#p8210):

> Seeing the interest, I now have plans to somehow recreate this on a cloud service and possibly rewrite it to use cloud functions/lambdas which have the potential to avoid certain costs.

Depending on how you were planning to approach this, I can see how the current move to an organization might interfere a bit with this plan, @eegeeZA. Please know that you have my full support if you still want to pursue this. It might or might not be better to do it on a separate clone, but you have my support in both cases.

It seems you also have the support of Josh.

[josh, Sat Aug 24, 2019 6:54 pm](https://bbs.spamgourmet.com/viewtopic.php?p=8214#p8214):

> If you have been working on starting up a similar service of any sort - personal/business/etc. -- don't stop! (unless you want to, of course).

**Comment by eegeeZA** [comment]
Pretty surprised to see how much discussion occurred in the past two days. But also glad to see the level of agreement and support. I have accepted the invitation and transferred the repository. @mikedlr I do have one request: can we please keep the repository called `spamgourmet-clone` for the time being? I would like people to know that this is just a clone of the SVN repo and not the official repository created by spamgourmet's Josh.

@jgonggrijp you can refer to me as he/him.

**Comment by nrbray** [comment]
> can we please keep the repository called spamgourmet-clone for the time being? I would like people to know that this is just a clone of the SVN repo and not the official repository created by spamgourmet's Josh.

I was inclined to the same view myself then subject to a greenlight to treat this as the official-repo I guess the name could be changed then

**Comment by mikedlr** [comment]
Hi;  I've set everyone in this ticket as a collaborator with at least "maintain" privileges.  I've set @eegeeZA as admin so he can also add collaborators in future if ever needed.  Completely fine with keeping the name spamgourmet-clone for now.

**Comment by jgonggrijp** [comment]
@mikedlr @eegeeZA @nrbray @shinyone Fast-forward two and a half months. I procrastinated on my promise to reach out to former and future maintainers. I'm sorry about this.

Fortunately, two forum admins became active on the spamgourmet bbs in the meanwhile. One of them is SysKoll, who has helped to maintain spamgourmet in the past. Judging from his responses in the help forum, he has resumed doing that (or maybe he never really stopped). The other is Josiah, the son of josh. He has officially [announced](https://bbs.spamgourmet.com/viewtopic.php?f=7&t=1793&p=8312#p8312) that he is taking over and will be opening spamgourmet for new users again sometime in the future.

I found out about this just now, and have sent an invitation to join us on GitHub to both of them. To be continued.
