### ISSUE TITLE
Josiah joining the team 🎈🎉

### ISSUE THREAD

**Issue by jgonggrijp** [spamgourmet/spamgourmet-clone#8]
@josiah-hamilton is the son of josh and the new official admin of spamgourmet.com. As discussed in #4, I invited him to join our organization and use this repo as the official repo. Happy news: he accepted our invitation!

Josiah expressed the wish to co-own the organization, i.e., to be an owner but not the only one. I think it would be natural for @mikedlr to stay as an owner and welcome Josiah beside him. Would you do that, @mikedlr?

If I may be so free, I would like to suggest that @eegeeZA be made a third owner of the organization, as an honour for converting the repository from SVN and for taking good care of the issues and pull requests since.

Once @josiah-hamilton is on board, we can also change the repo name to just "spamgourmet", since it will be the official repo from then onwards.

**Comment by eegeeZA** [comment]
Welcome, Josiah! I have invited you to this repository as an administrator. I cannot, however, add you to the organisation as I lack the permissions. Please let me know if you need any assistance in updating this repository with the code you have access to. Otherwise, I can also assist in creating a new repository if that is easier or preferred.

**Comment by mikedlr** [comment]
@josiah-hamilton has been invited to the organisation - hopefully he accepts.

**Comment by jgonggrijp** [comment]
@josiah-hamilton If the invitation email is lost, you can still see the invitation over here:

https://github.com/orgs/spamgourmet/invitation
